#!/bin/sh
set -e

# /etc/init.d/xbeinstd: start and stop the XBE instance daemon

export PYTHONPATH="$PYTHONPATH":/root/xenbee/modules
daemon=/root/xenbee/bin/xbeinstd
pidfile=/var/run/xbeinstd.pid

test -x $daemon || exit 0

if test -f /etc/default/xbeinstd; then
    . /etc/default/xbeinstd
fi

. /lib/lsb/init-functions

#check_config() { }

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
	log_begin_msg "Starting XenBEE instance daemon..."
	start-stop-daemon --start --quiet -b -m --pidfile $pidfile --exec $daemon -- $XBEINSTD_OPTS || log_end_msg 1
	log_end_msg 0
	;;
  stop)
	log_begin_msg "Stopping XenBEE instance daemon..."
	start-stop-daemon --stop --quiet --oknodo --pidfile $pidfile || log_end_msg 1
	log_end_msg 0
	;;

  reload|force-reload)
	log_begin_msg "Reloading XenBEE instance daemon..."
	check_config
	start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile $pidfile --exec $daemon || log_end_msg 1
	log_end_msg 0
	;;

  restart)
	log_begin_msg "Restarting XenBEE instance daemon..."
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $pidfile
	start-stop-daemon --start --quiet -b -m --pidfile $pidfile --exec $daemon -- $XBEINSTD_OPTS || log_end_msg 1
	log_end_msg 0
	;;

  *)
	log_success_msg "Usage: /etc/init.d/xbeinstd {start|stop|reload|force-reload|restart}"
	exit 1
esac

exit 0
