// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "seda-msg.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace seda {
namespace comm {

namespace {

const ::google::protobuf::Descriptor* Message_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Message_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_seda_2dmsg_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  Message_descriptor_ = file->message_type(0);
  Message::default_instance_ = new Message();
  static const int Message_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, to_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, from_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, payload_),
  };
  Message_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Message_descriptor_,
      Message::default_instance_,
      Message_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Message, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Message));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Message_descriptor_, Message::default_instance_);
  Message::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_seda_2dmsg_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\016seda-msg.proto\022\tseda.comm\"4\n\007Message\022\n"
    "\n\002to\030\001 \002(\t\022\014\n\004from\030\002 \002(\t\022\017\n\007payload\030\003 \002("
    "\014", 81,
  &protobuf_BuildDesc_seda_2dmsg_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_seda_2dmsg_2eproto {
  StaticDescriptorInitializer_seda_2dmsg_2eproto() {
    protobuf_BuildDesc_seda_2dmsg_2eproto();
  }
} static_descriptor_initializer_seda_2dmsg_2eproto_;


// ===================================================================

const ::std::string Message::_default_to_;
const ::std::string Message::_default_from_;
const ::std::string Message::_default_payload_;
Message::Message()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    to_(const_cast< ::std::string*>(&_default_to_)),
    from_(const_cast< ::std::string*>(&_default_from_)),
    payload_(const_cast< ::std::string*>(&_default_payload_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Message::InitAsDefaultInstance() {}

Message::Message(const Message& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    to_(const_cast< ::std::string*>(&_default_to_)),
    from_(const_cast< ::std::string*>(&_default_from_)),
    payload_(const_cast< ::std::string*>(&_default_payload_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Message::~Message() {
  if (to_ != &_default_to_) {
    delete to_;
  }
  if (from_ != &_default_from_) {
    delete from_;
  }
  if (payload_ != &_default_payload_) {
    delete payload_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Message::descriptor() {
  if (Message_descriptor_ == NULL) protobuf_BuildDesc_seda_2dmsg_2eproto();
  return Message_descriptor_;
}

const Message& Message::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_seda_2dmsg_2eproto();
  return *default_instance_;
}

Message* Message::default_instance_ = NULL;

Message* Message::New() const {
  return new Message;
}

const ::google::protobuf::Descriptor* Message::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Message::GetReflection() const {
  if (Message_reflection_ == NULL) protobuf_BuildDesc_seda_2dmsg_2eproto();
  return Message_reflection_;
}

}  // namespace comm
}  // namespace seda
