#! /bin/sh
# 
# Bootstrap the project from a clean checkout.
#
if test -d "build"; then
	echo "build directory does already exist, aborting!" > /dev/stderr
	exit 1
else
	mkdir build && cd build && cmake ..
fi
